name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create Tag and Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          TAG_NAME="v$(date +'%Y.%m.%d.%H.%M')"
          node create-tag.js
